In [1]:
# 1. Importar as bibliotecas necessárias
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

caminho = "H:\Meu Drive\PESSOAL\PROJETOS\Processo-DataLP-Files\wetransfer_channels-csv_2025-11-06_1241\orders.csv"

# 2. Carregar o arquivo local para um DataFrame
df = pd.read_csv(caminho)

<>:6: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:6: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\infor77\AppData\Local\Temp\ipykernel_10972\3255037905.py:6: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  caminho = "H:\Meu Drive\PESSOAL\PROJETOS\Processo-DataLP-Files\wetransfer_channels-csv_2025-11-06_1241\orders.csv"

In [2]:
df.head(5)

,order_id,store_id,channel_id,payment_order_id,delivery_order_id,order_status,order_amount,order_delivery_fee,order_delivery_cost,order_created_hour,...,order_moment_delivering,order_moment_delivered,order_moment_finished,order_metric_collected_time,order_metric_paused_time,order_metric_production_time,order_metric_walking_time,order_metric_expediton_speed_time,order_metric_transit_time,order_metric_cycle_time
0,68405119,3512,5,68405119,68405119,CANCELED,62.7,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68405123,3512,5,68405123,68405123,CANCELED,62.7,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68405206,3512,5,68405206,68405206,CANCELED,115.5,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,68405465,3401,5,68405465,68405465,CANCELED,55.9,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,68406064,3401,5,68406064,68406064,CANCELED,37.9,0.0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.describe()

,order_id,store_id,channel_id,payment_order_id,delivery_order_id,order_amount,order_delivery_fee,order_delivery_cost,order_created_hour,order_created_minute,order_created_day,order_created_month,order_created_year,order_metric_collected_time,order_metric_paused_time,order_metric_production_time,order_metric_walking_time,order_metric_expediton_speed_time,order_metric_transit_time,order_metric_cycle_time
count,3.689990e+05,368999.000000,368999.000000,3.689990e+05,3.689990e+05,3.689990e+05,368999.000000,361794.000000,368999.000000,368999.000000,368999.000000,368999.000000,368999.0,317507.000000,297594.000000,343892.000000,294943.000000,334417.000000,343142.000000,353380.000000
mean,8.230726e+07,1197.796124,7.837929,8.230726e+07,8.230726e+07,1.051513e+02,6.178904,7.285869,16.719612,29.441210,15.965265,2.690690,2021.0,2.755433,9.185759,61.789895,4.773946,19.081852,46.849637,156.567920
std,7.037735e+06,1151.075389,8.298331,7.037735e+06,7.037735e+06,2.953111e+03,6.222460,4.075295,6.095596,17.223663,8.827469,1.100082,0.0,13.232567,65.722750,802.996121,17.578862,88.241935,752.577933,1224.987559
min,6.840512e+07,3.000000,1.000000,6.840512e+07,6.840512e+07,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,2021.0,-1.470000,-2728.350000,0.000000,-1.420000,-0.820000,-4.100000,0.330000
25%,7.635522e+07,415.000000,5.000000,7.635522e+07,7.635522e+07,3.990000e+01,0.000000,5.160000,15.000000,15.000000,8.000000,2.000000,2021.0,0.780000,1.170000,8.930000,2.150000,4.480000,11.830000,32.870000
50%,8.324599e+07,707.000000,5.000000,8.324599e+07,8.324599e+07,7.160000e+01,6.900000,7.190000,17.000000,29.000000,16.000000,3.000000,2021.0,1.670000,2.500000,15.170000,3.570000,6.600000,16.720000,42.230000
75%,8.803055e+07,1528.000000,5.000000,8.803055e+07,8.803055e+07,1.219000e+02,11.900000,8.720000,22.000000,44.000000,24.000000,4.000000,2021.0,3.030000,5.370000,22.230000,5.430000,10.330000,24.730000,55.670000
max,9.313982e+07,4679.000000,49.000000,9.313982e+07,9.313982e+07,1.788306e+06,990.110000,156.000000,23.000000,59.000000,31.000000,4.000000,2021.0,2050.400000,11712.280000,85662.030000,2735.520000,11718.200000,154261.100000,154277.320000

In [4]:
df.dtypes

order_id                               int64
store_id                               int64
channel_id                             int64
payment_order_id                       int64
delivery_order_id                      int64
order_status                          object
order_amount                         float64
order_delivery_fee                   float64
order_delivery_cost                  float64
order_created_hour                     int64
order_created_minute                   int64
order_created_day                      int64
order_created_month                    int64
order_created_year                     int64
order_moment_created                  object
order_moment_accepted                 object
order_moment_ready                    object
order_moment_collected                object
order_moment_in_expedition            object
order_moment_delivering               object
order_moment_delivered                object
order_moment_finished                 object
order_metric_collected_time          float64
order_metric_paused_time             float64
order_metric_production_time         float64
order_metric_walking_time            float64
order_metric_expediton_speed_time    float64
order_metric_transit_time            float64
order_metric_cycle_time              float64
dtype: object

In [5]:
#Contando valores nulos 
df.isnull().sum()

order_id                                  0
store_id                                  0
channel_id                                0
payment_order_id                          0
delivery_order_id                         0
order_status                              0
order_amount                              0
order_delivery_fee                        0
order_delivery_cost                    7205
order_created_hour                        0
order_created_minute                      0
order_created_day                         0
order_created_month                       0
order_created_year                        0
order_moment_created                      0
order_moment_accepted                  9461
order_moment_ready                    25106
order_moment_collected                42894
order_moment_in_expedition            67429
order_moment_delivering               25316
order_moment_delivered               349398
order_moment_finished                 15599
order_metric_collected_time           51492
order_metric_paused_time              71405
order_metric_production_time          25107
order_metric_walking_time             74056
order_metric_expediton_speed_time     34582
order_metric_transit_time             25857
order_metric_cycle_time               15619
dtype: int64

In [6]:
df.isnull().sum() / len(df) * 100

order_id                              0.000000
store_id                              0.000000
channel_id                            0.000000
payment_order_id                      0.000000
delivery_order_id                     0.000000
order_status                          0.000000
order_amount                          0.000000
order_delivery_fee                    0.000000
order_delivery_cost                   1.952580
order_created_hour                    0.000000
order_created_minute                  0.000000
order_created_day                     0.000000
order_created_month                   0.000000
order_created_year                    0.000000
order_moment_created                  0.000000
order_moment_accepted                 2.563964
order_moment_ready                    6.803812
order_moment_collected               11.624422
order_moment_in_expedition           18.273491
order_moment_delivering               6.860723
order_moment_delivered               94.688061
order_moment_finished                 4.227383
order_metric_collected_time          13.954509
order_metric_paused_time             19.351001
order_metric_production_time          6.804083
order_metric_walking_time            20.069431
order_metric_expediton_speed_time     9.371841
order_metric_transit_time             7.007336
order_metric_cycle_time               4.232803
dtype: float64

In [7]:
df.describe(include=['object', 'bool']) # 'object' para strings, 'bool' para booleanos

,order_status,order_moment_created,order_moment_accepted,order_moment_ready,order_moment_collected,order_moment_in_expedition,order_moment_delivering,order_moment_delivered,order_moment_finished
count,368999,368999,359538,343893,326105,301570,343683,19601,353400
unique,2,340934,343900,328458,313259,290327,328727,19523,336815
top,FINISHED,3/13/2021 12:04:08 AM,4/2/2021 3:25:08 PM,3/11/2021 4:00:25 PM,4/25/2021 10:47:26 PM,3/12/2021 3:38:00 PM,4/16/2021 3:52:41 PM,3/27/2021 1:05:58 AM,1/25/2021 8:20:02 PM
freq,352020,6,5,6,5,5,6,4,13